name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Generate Snake SVG
      uses: Platane/snk/svg-only@v3
      with:
        github_user_name: sumantpolai
        outputs: dist/github-contribution-grid-snake.svg

    # Ensure the directory exists and list the contents
    - run: |
        mkdir -p dist  # Ensure the dist directory exists
        ls -la dist  # List contents of the dist directory to confirm

    # Push the changes to the output branch
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
        force: true

    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.1.3
      with:
        target_branch: output
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
